### PR TITLE
Normalize development section

### LINKED ISSUE #118: Development Section of the Project Site
We need to normalize the URLs for the project sites.

Rename:

- [ ] reports/debug/ >>>> development/coverage/
- [ ] reports/javadoc/ >>>> development/code-documentation/
- [ ] reports/androidTests/connected/ >>>> development/test-reports/

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Change the workflow to update the changelog when there is a merge in master branch
Rename folders in development section for normalization
Remove the header generation in Changelog

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Closes #118 
Depends on #159

### CODE REVIEW

**Comment by Naylin15** [comment]
The documentation is changed as it should, it's the same with the release

However broken links that went undetected before by html-proofer are now presenting failures

For example:

According to the past issue #30  we must rename the following file to index

```overview-summary.html -> index.html```

There are files that have links to the old name

- [Help doc containing link to Overview](http://flyve.org/android-inventory-agent/reports/javadoc/help-doc.html)

And in past builds from CI there is no failure regarding them

- [1555](https://circleci.com/gh/flyve-mdm/android-inventory-agent/1555#tests/containers/1)
- [1530](https://circleci.com/gh/flyve-mdm/android-inventory-agent/1530#tests/containers/1)
- [1523](https://circleci.com/gh/flyve-mdm/android-inventory-agent/1523#tests/containers/1)

Though the broken link is present

- [Broken link on project site](http://flyve.org/android-inventory-agent/reports/javadoc/overview-summary.html)

Related [#464](https://git.io/vhPB9)

**Comment by Naylin15** [comment]
HI, @ajsb85 @rafaelje 

This PR is ready

As with the PR in android-mdm-agent repository I renamed the variables starting with GH to keep consistency and I'll proceed to delete them on Circle CI once this PR is merged

To delete:

GH_TOKEN
GH_USER
GH_EMAIL

Renamed to:

GITHUB_TOKEN
GITHUB_USER
GITHUB_EMAIL

Thank you

**Comment by ajsb85** [comment]
Hi, @Naylin15 
There are the environment variables:
https://circleci.com/gh/flyve-mdm/android-inventory-agent/edit#env-vars

**Comment by Naylin15** [comment]
Hi, @ajsb85 @rafaelje 

The old variables are now removed

[Environment Variables](https://circleci.com/gh/flyve-mdm/android-inventory-agent/edit#env-vars)

**Pull request merged**
